# Generated by Django 5.2.3 on 2025-06-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_material_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='verification_code',
            field=models.CharField(default='temp-code', max_length=100),
            preserve_default=False,
        ),
    ]
