# Generated by Django 5.2.3 on 2025-06-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_material_hub', '0002_studymaterial_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
