# Generated by Django 5.2.3 on 2025-06-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_material_hub', '0004_emailotp_delete_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Reader', 'Reader'), ('Uploader', 'Uploader')], default='Reader', max_length=10),
        ),
    ]
