# Generated by Django 5.2.3 on 2025-07-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_material_hub', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaderprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='uploaderprofile',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
