# Generated by Django 5.2.3 on 2025-07-01 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_material_hub', '0006_remove_uploaderprofile_address_uploaderprofile_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
