# Generated by Django 5.2.3 on 2025-07-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_material_hub', '0010_material_savedmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
