# Generated by Django 5.2.3 on 2025-07-04 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_material_hub', '0011_material_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_material_hub.studymaterial'),
        ),
        migrations.AlterField(
            model_name='savedmaterial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
